export const TOGGLE_SOUND = 'TOGGLE_SOUND';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CHANGE_STEP = 'CHANGE_STEP';

export const SET_ANSWERS_STATE = 'SET_ANSWERS_STATE';
export const IS_ANSWERED = 'IS_ANSWERED';

export const ADD_ANSWER = 'ADD_ANSWER';
export const GET_ANSWERS = 'GET_ANSWERS';

export const PARSE_RESULTS = 'PARSE_RESULTS';
export const LOAD_ANSWERS = 'LOAD_ANSWERS';